export * from './types'
export { syllabifyWord, detectStress, analyzeWord } from './syllabify'
export { hasSinalefa } from './sinalefa'
export { normalizePhoneticTail, vowelsOnly } from './phonetics'
export { tokenizeVerse, analyzeVerse } from './verse'
export { analyzeMetricFeet, describeFeetPattern, hyphenateStressPattern, metricFootName, metricStressSymbol, verseStresses, METRIC_FOOT_NAMES } from './feet'
export { computeRhymeScheme } from './rhyme'
export { verseTypeName, classifyRhymePattern } from './classify'
